name: bulild test
on:
  push:
    branches:
      - master

jobs:
  build:
    name: build test
    runs-on: macos-latest
    strategy:
      matrix:
        destination: ["platform=iOS Simulator,OS=13.6,name=iPhone 11 Pro"]
        xcode: ["/Applications/Xcode_11.6.app/Contents/Developer"]
    steps:
      - name: checkout source
        uses: actions/checkout@v2

      - name: switch command line tools
        run: sudo xcode-select -s /Applications/Xcode_11.6.app

#       - name: üç´ Cache Pods
#         id: cache-pods
#         uses: actions/cache@v1.1.2
#         with:
#           path: Pods
#           key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
#           restore-keys: |
#             ${{ runner.os }}-pods-
            
#       - name: üì¶ Build Pods
#         if: steps.cache-pods.outputs.cache-hit != 'true'
#         run: pod install

      - name: üì¶ build simulator app
        run: xcodebuild -derivedDataPath ./DerivedData -workspace AppStoreSearch.xcworkspace -scheme "AppStoreSearch" -destination "${destination}"
        env:
          destination: ${{ matrix.destination }}
